### ISSUE TITLE
Three things

### ISSUE THREAD

**Issue by milkdropper** [OfficialIncubo/The-Improved-and-Modified-Version-of-BeatDrop-Music-Visualizer#2]
I thought I submitted this issue already but can't see it now. If I duplicated anything, sorry.

I have three things:
1) It's great you are moving this project forward! It seems the original maintainer has gone silent.
2) Could you implement this PR for multiple monitor support? https://github.com/mvsoft74/BeatDrop/pull/4
3) Can you give an option to toggle unlimited FPS? I am on a 244hz monitor and getting 200+FPS. This looks really nice for some presets, but others act like they are going way too fast. This is because many presets are based on the FPS counter which is expected to be 60 and were designed originally on 60.

Thanks!

**Comment by milkdrop2077** [comment]
hey milkdropper, 
I can't test the unlimited FPS feature because my screen only support 60fps, do you have the same problem with my version BeatDrop2077? I could implement an option for that. Do you have this problem with the milkdrop version of wacup? it's limited to 144fps, maybe I should look into it.

**Comment by milkdrop2077** [comment]
Also I've implemented your ALT+SHIFT stretching code into my version of BeatDrop2077, it seems to work well but I don't have multiple monitor to test it so please let me know if it works like it should be!

**Comment by milkdrop2077** [comment]
> I thought I submitted this issue already but can't see it now. If I duplicated anything, sorry.
> 
> I have three things:
> 
>     1. It's great you are moving this project forward! It seems the original maintainer has gone silent.
> 
>     2. Could you implement this PR for multiple monitor support? [Implement support for multiple monitors mvsoft74/BeatDrop#4](https://github.com/mvsoft74/BeatDrop/pull/4)
> 
>     3. Can you give an option to toggle unlimited FPS? I am on a 244hz monitor and getting 200+FPS. This looks really nice for some presets, but others act like they are going way too fast. This is because many presets are based on the FPS counter which is expected to be 60 and were designed originally on 60.
> 
> 
> Thanks!

Also I've implemented your ALT+SHIFT stretching code into my version of BeatDrop2077, it seems to work well but I don't have multiple monitor to test it so please let me know if it works like it should be!

**Comment by Se7enSlasher** [comment]
My laptop's monitor runs 144 FPS on it because it has 144hz.
I should do an action, such as multiple monitor stretch and always on top feature while I come back home.

**Comment by Se7enSlasher** [comment]
Done! Look at these commits:
- https://github.com/mvsoft74/BeatDrop/commit/d3691c029d833da07dd39e1a6e036e6c983c3b96 (Always On Top)
- https://github.com/mvsoft74/BeatDrop/commit/89f95cdc47e8c655cf38be36209401474d85796e (Multiple Monitor Stretch)

**Comment by Se7enSlasher** [comment]
Ok, @milkdropper, for toggling the Unlimited FPS on and off, what hotkey should I specify?

When off, the framerate should change to 0 to the max_fps_w and max_fps_fs read from milk2.ini.

**Comment by OfficialIncubo** [comment]
Alright. @milkdrop2077 now implemented this feature and this code will be released in the future or later (F3 hotkey).

I will close this issue right now.

**Comment by OfficialIncubo** [comment]
Hey, @milkdropper! I have implemented my own version of toggle 30/60/90... fps! You can check my commit now: https://github.com/mvsoft74/BeatDrop/commit/75af8fdcc92ff19df92a3dd8620682a622328f57

So, It's very easy for me to implement it.

**Comment by OfficialIncubo** [comment]
Eh, how about closing this because it's done!
